app/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    return Excel::download(new \App\Exports\DanhGiaTheoLopExports(), 'lophoc.pdf', Excel::DOMPDF);
     return redirect('/sv');
})->name('index');

Route::get('redirect/{driver}', 'Auth\LoginController@redirectToProvider')
    ->name('login.provider')
    ->where('driver', implode('|', config('auth.socialite.drivers')));
Route::get('/callback/{driver}', 'Auth\LoginController@handleProviderCallback');
Route::post('auth/logout', 'Auth\LoginController@logout')->middleware('auth')->name('logout.custom');

Route::get('doi-hoc-ky/{idHocKy}', 'Auth\AuthController@changeHocKy')
    ->name('doiHocKy')->middleware('auth');


Route::prefix('common')->name('common.')->group(function () {
    Route::get('diem-ren-luyen/api/thong-ke', 'CommonController@thongKeTheoLop')->middleware(['auth']);
    Route::get('diem-ren-luyen/api/bao-cao-excel', 'CommonController@baoCaoExcelTheoLop')->middleware(['auth']);
    // Route::get('roles-user', 'CommonController@roles')->middleware(['auth', 'role:super_admin']);
});

Route::get('/sv', function () {
    if (Auth::check()) {
        return Auth::user();
        return redirect()->route('sv.danh-gia.index');
    }
    return view('auth.sv.login');
})->name('sv.login');

Route::prefix('sv')->name('sv.')->middleware(['auth'])->group(function () {

    Route::get('danh-gia/api', 'EndUser\DanhGiaController@sinhVienGetDotDanhGiaHienTai');
    Route::get('danh-gia/api/dot-danh-gia', 'EndUser\DanhGiaController@sinhVienGetDotDanhGiaHienTai');
    Route::resource('danh-gia', EndUser\DanhGiaController::class);

    Route::prefix('cbl')->name('cbl.')->middleware(['loptruong'])->group(function () {
        Route::get('danh-gia/api', 'EndUser\CBLQuanLyController@getDSDanhGia');
        Route::get('danh-gia/api/sinh-vien/{id}', 'EndUser\CBLQuanLyController@sinhVienGetDotDanhGiaHienTai');
        Route::post('danh-gia/api/sinh-vien/{id}', 'EndUser\CBLQuanLyController@sinhVienDanhGiaDotDanhGiaHienTai');
        Route::resource('danh-gia', EndUser\CBLQuanLyController::class);
    });

});

Route::get('/gv', function () {
    if (Auth::check()) {
        return redirect()->route('gv.diem-ren-luyen.index');
    }
    return view('auth.gv.login');
})->name('gv.login');

Route::prefix('gv')->name('gv.')->middleware(['auth', 'gv'])->group(function () {

    Route::get('diem-ren-luyen/api/lop', 'EndUser\GVController@getLop');
    Route::get('diem-ren-luyen/api/sinh-vien/{id}', 'EndUser\GVController@GVGetDotDanhGiaHienTai');
    Route::put('diem-ren-luyen/api/nhan-xet/{id}', 'EndUser\GVController@nhanXetSV');
    Route::put('diem-ren-luyen/api/duyet/{id}', 'EndUser\GVController@duyetSV');
    Route::get('diem-ren-luyen/api', 'EndUser\GVController@danhSachDiemRenLuyenLop');

    Route::resource('diem-ren-luyen', EndUser\GVController::class);

});

Route::get('/admin', function () {
    if (Auth::check()) {
        return redirect()->route('admin.DM_DiemRenLuyen.index');
    }
    return view('auth.gv.login');
})->name('admin.login');

Route::prefix('admin')->name('admin.')->middleware(['auth', 'gv'])->group(function () {

    Route::get('DM_MauTieuChi/api', 'Admin\DM_MauTieuChi_Controller@getData');

    Route::put('DM_MauTieuChi/{idMauTieuChi}/update-tieuchi', 'Admin\DM_MauTieuChi_Controller@updateChiTiet');
    Route::get('DM_MauTieuChi/{idMauTieuChi}/tieuchi-chitiet', 'Admin\DM_MauTieuChi_Controller@getTieuChiChiTiet');

    Route::resource('DM_MauTieuChi', Admin\DM_MauTieuChi_Controller::class);

    Route::get('DM_DiemRenLuyen/api', 'Admin\DM_DiemRenLuyen_Controller@danhSachDiemRenLuyenLop');
    Route::get('DM_DiemRenLuyen/api/danh-gia-sv/{id}', 'Admin\DM_DiemRenLuyen_Controller@getDanhGiaSV');

    Route::resource('DM_DiemRenLuyen', Admin\DM_DiemRenLuyen_Controller::class);

    Route::get('DM_LopHoc/api', 'Admin\DM_LopHoc_Controller@getData');
    Route::resource('DM_LopHoc', Admin\DM_LopHoc_Controller::class);

    Route::get('DM_DotDanhGia/api', 'Admin\DM_HocKy_Controller@getData');
    Route::get('DM_DotDanhGia/api/hocky', 'Admin\DM_HocKy_Controller@getHocKy');
    Route::put('DM_DotDanhGia/api/khoa/{id}', 'Admin\DM_HocKy_Controller@updateKhoa');
    Route::put('DM_DotDanhGia/api/update-hienhanh/{id}', 'Admin\DM_HocKy_Controller@updateHienHanh');

    Route::get('DM_DotDanhGia/api/sync-data', 'Admin\DM_HocKy_Controller@syncHocKy');

    Route::resource('DM_DotDanhGia', Admin\DM_HocKy_Controller::class);

    Route::resource('DM_GiangVien', Admin\DM_GiangVien_Controller::class);

    Route::resource('DM_SinhVien', Admin\DM_SinhVien_Controller::class);

    Route::get('nguoi-dung', function () {
       return view('admin.index');
    })->name('nguoi-dung.index');
    Route::put('user/change-role-sv/{id}', 'UserController@changeRuleSV');
    Route::resource('user', UserController::class);
});

Auth::routes([
    'register' => false,
    'verify' => false,
    'reset' => false,
    'confirm' => false
]);

Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');

app/app/Models/SV.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use App\Models\DM_LopHoc;

class SV extends Model
{

    // use SoftDeletes;

    protected $table = 'table_sinhvien';
    public static $snakeAttributes = false;

    protected $fillable = [
        // 'id',
        // 'masv',
        // 'hodem',
        // 'ten',
        // 'ngaysinh',
        // 'gioitinh',
        // 'dienthoai',
        // 'dienthoaigiadinh',
        // 'khoahoc_id',
        // 'lopsh_id',
        // 'nganh_id',
        // 'ctdt_id',
        // 'trangthai',
        // 'is_tn',
        // 'ghichu',
    ];

    protected $casts = [
        'created_at' => 'timestamp',
        'updated_at' => 'timestamp'
    ];

    protected $hidden = [
        'deleted_at', 'created_at', 'updated_at', 'remember_token', 'diem_dauvao', 'pt_ts', 'type', 'thechat',
        'quocphong', 'ngoaingu', 'tinhoc'
    ];

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'masv', 'username');
    }

    public function lopHoc()
    {
        return $this->belongsTo(DM_LopHoc::class, 'lopsh_id');
    }

    public function danhGia() {
        return $this->hasOne(DanhGiaChiTiet::class, 'MaSV', 'masv');
    }

}

app/resources/views/layouts/sv/header.blade.php
<div>
    <nav class="navbar navbar-light bg-white" id='nav'>
        <div class="container-fluid d-flex align-items-center justify-content-between">
            <div>
                <i class='fa fa-bars' style='font-size: 26px; cursor: pointer' onClick='openSider()'> </i>
            </div>
            {{-- <div><span>Học kỳ 1 năm 2021 - 2022</span></div> --}}
            @php
                use App\Models\DM_DotDanhGia; 
                $hienHanh = DM_DotDanhGia::where('HienHanh', 1)->with('hocKy')->first();
                if (!empty($hienHanh)) echo("<div><span>Học kỳ {$hienHanh->hocKy->hocky} năm học {$hienHanh->hocKy->nambatdau} - {$hienHanh->hocKy->namketthuc}</span></div>")
            @endphp
            <div class='nav-right position-relative'>
                <div onClick='openDropdown()'>
                    <img class='rounded-circle' src='/images/logo.png' />
                    <span>
                        @if (!empty(Session::get('sv')))
                            {{ Session::get('sv')->hodem }} {{ Session::get('sv')->ten }} - {{ Session::get('sv')->lopHoc->tenlop  }}
                        @endif
                    </span>
                </div>
                <div id="drop-down" class='position-absolute user-dropdown d-none'>
                    <div>
                        <div class='dropdown-arrow' style="
                        position: absolute;
                        display: block;
                        width: 8.5px;
                        background: transparent;
                        height: 8.5px;
                        border: 4.25px solid white;
                        transform: rotate(45deg);
                        /* z-index: -1; */
                        top: -5px;
                        left: 71px;
                    "></div>
                        <div class='user-dropdown-content bg-white '
                        style='box-shadow: rgb(0 0 0 / 20%) 0px 2px 10px; border-radius: 4px; '>
                            <a  href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();"
                                class='dropdown-tag w-100 d-flex' style="padding: 7px 15px">
                                <span><i class='fa fa-sign-out'></i></span>
                                <span class="ps-2">Logout</span>
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

app/resources/views/layouts/sv/sidebar.blade.php
<div class="h-100 openSider sider position-relative" id='sider' style='background-color: #2A3F54;'>
    <div class="text-center logo-container">
        <h3 class='m-0'>
            <a href="/" class='text-decoration-none text-white text-uppercase'>VKU</a>
        </h3>
    </div>
    <div class='position-relative w-100 menu-wrap sidebar-left' style='height: calc(100% - 70px); max-height: calc(100% - 70px);'>
        <div class='position-absolute top-0'
            style='position: absolute; top: 0px; left: 0px; right: 0px; bottom: 0px; margin-right: 0px; margin-bottom: 0px;'>
            <ul class='py-4 ' id='siderbar'>
                <li class='d-block'>
                    <a class='text-decoration-none text-white' href="{{ route('sv.danh-gia.index') }}">
                        <span style='color: rgb(120, 129, 149)'>
                            <i class='fa fa-street-view'></i>
                            <span class='ps-2' id='menu-text'>Đánh giá điểm rèn luyện</span>
                        </span>
                    </a>
                </li>
                @if (Session::get('loptruong'))
                    <li class='d-block'>
                        <a class='text-decoration-none text-white' href="{{ route('sv.cbl.danh-gia.index') }}">
                            <span style='color: rgb(120, 129, 149)' class='d-flex '>
                                <i class='fa fa-street-view'></i>
                                <span class='ps-2 d-none d-sm-none d-md-block d-lg-block d-xl-block' id='menu-text'>CBL đánh giá</span>
                            </span>
                        </a>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</div>

@section('js')
    @parent
    <script>
        function openSider() {
            document.getElementById("sider")?.classList.toggle('openSider');


        }

    </script>
    <script>

</script>
@endsection