app/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    return Excel::download(new \App\Exports\DanhGiaTheoLopExports(), 'lophoc.pdf', Excel::DOMPDF);
     return redirect('/sv');
})->name('index');

Route::get('redirect/{driver}', 'Auth\LoginController@redirectToProvider')
    ->name('login.provider')
    ->where('driver', implode('|', config('auth.socialite.drivers')));
Route::get('/callback/{driver}', 'Auth\LoginController@handleProviderCallback');
Route::post('auth/logout', 'Auth\LoginController@logout')->middleware('auth')->name('logout.custom');

Route::get('doi-hoc-ky/{idHocKy}', 'Auth\AuthController@changeHocKy')
    ->name('doiHocKy')->middleware('auth');


Route::prefix('common')->name('common.')->group(function () {
    Route::get('diem-ren-luyen/api/thong-ke', 'CommonController@thongKeTheoLop')->middleware(['auth']);
    Route::get('diem-ren-luyen/api/bao-cao-excel', 'CommonController@baoCaoExcelTheoLop')->middleware(['auth']);
    // Route::get('roles-user', 'CommonController@roles')->middleware(['auth', 'role:super_admin']);
});

Route::get('/sv', function () {
    if (Auth::check()) {
        return Auth::user();
        return redirect()->route('sv.danh-gia.index');
    }
    return view('auth.sv.login');
})->name('sv.login');

Route::prefix('sv')->name('sv.')->middleware(['auth'])->group(function () {

    Route::get('danh-gia/api', 'EndUser\DanhGiaController@sinhVienGetDotDanhGiaHienTai');
    Route::get('danh-gia/api/dot-danh-gia', 'EndUser\DanhGiaController@sinhVienGetDotDanhGiaHienTai');
    Route::resource('danh-gia', EndUser\DanhGiaController::class);

    Route::prefix('cbl')->name('cbl.')->middleware(['loptruong'])->group(function () {
        Route::get('danh-gia/api', 'EndUser\CBLQuanLyController@getDSDanhGia');
        Route::get('danh-gia/api/sinh-vien/{id}', 'EndUser\CBLQuanLyController@sinhVienGetDotDanhGiaHienTai');
        Route::post('danh-gia/api/sinh-vien/{id}', 'EndUser\CBLQuanLyController@sinhVienDanhGiaDotDanhGiaHienTai');
        Route::resource('danh-gia', EndUser\CBLQuanLyController::class);
    });

});

Route::get('/gv', function () {
    if (Auth::check()) {
        return redirect()->route('gv.diem-ren-luyen.index');
    }
    return view('auth.gv.login');
})->name('gv.login');

Route::prefix('gv')->name('gv.')->middleware(['auth', 'gv'])->group(function () {

    Route::get('diem-ren-luyen/api/lop', 'EndUser\GVController@getLop');
    Route::get('diem-ren-luyen/api/sinh-vien/{id}', 'EndUser\GVController@GVGetDotDanhGiaHienTai');
    Route::put('diem-ren-luyen/api/nhan-xet/{id}', 'EndUser\GVController@nhanXetSV');
    Route::put('diem-ren-luyen/api/duyet/{id}', 'EndUser\GVController@duyetSV');
    Route::get('diem-ren-luyen/api', 'EndUser\GVController@danhSachDiemRenLuyenLop');

    Route::resource('diem-ren-luyen', EndUser\GVController::class);

});

Route::get('/admin', function () {
    if (Auth::check()) {
        return redirect()->route('admin.DM_DiemRenLuyen.index');
    }
    return view('auth.gv.login');
})->name('admin.login');

Route::prefix('admin')->name('admin.')->middleware(['auth', 'gv'])->group(function () {

    Route::get('DM_MauTieuChi/api', 'Admin\DM_MauTieuChi_Controller@getData');

    Route::put('DM_MauTieuChi/{idMauTieuChi}/update-tieuchi', 'Admin\DM_MauTieuChi_Controller@updateChiTiet');
    Route::get('DM_MauTieuChi/{idMauTieuChi}/tieuchi-chitiet', 'Admin\DM_MauTieuChi_Controller@getTieuChiChiTiet');

    Route::resource('DM_MauTieuChi', Admin\DM_MauTieuChi_Controller::class);

    Route::get('DM_DiemRenLuyen/api', 'Admin\DM_DiemRenLuyen_Controller@danhSachDiemRenLuyenLop');
    Route::get('DM_DiemRenLuyen/api/danh-gia-sv/{id}', 'Admin\DM_DiemRenLuyen_Controller@getDanhGiaSV');

    Route::resource('DM_DiemRenLuyen', Admin\DM_DiemRenLuyen_Controller::class);

    Route::get('DM_LopHoc/api', 'Admin\DM_LopHoc_Controller@getData');
    Route::resource('DM_LopHoc', Admin\DM_LopHoc_Controller::class);

    Route::get('DM_DotDanhGia/api', 'Admin\DM_HocKy_Controller@getData');
    Route::get('DM_DotDanhGia/api/hocky', 'Admin\DM_HocKy_Controller@getHocKy');
    Route::put('DM_DotDanhGia/api/khoa/{id}', 'Admin\DM_HocKy_Controller@updateKhoa');
    Route::put('DM_DotDanhGia/api/update-hienhanh/{id}', 'Admin\DM_HocKy_Controller@updateHienHanh');

    Route::get('DM_DotDanhGia/api/sync-data', 'Admin\DM_HocKy_Controller@syncHocKy');

    Route::resource('DM_DotDanhGia', Admin\DM_HocKy_Controller::class);

    Route::resource('DM_GiangVien', Admin\DM_GiangVien_Controller::class);

    Route::resource('DM_SinhVien', Admin\DM_SinhVien_Controller::class);

    Route::get('nguoi-dung', function () {
       return view('admin.index');
    })->name('nguoi-dung.index');
    Route::put('user/change-role-sv/{id}', 'UserController@changeRuleSV');
    Route::resource('user', UserController::class);
});

Auth::routes([
    'register' => false,
    'verify' => false,
    'reset' => false,
    'confirm' => false
]);

Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');

app/resources/views/layouts/admin/header.blade.php
<div>
    <nav class="navbar navbar-light bg-white" id='nav'>
        <div class="container-fluid d-flex align-items-center justify-content-between">
            <div>
                <i class='fa fa-bars' style='font-size: 26px; cursor: pointer' onClick='openSider()'> </i>
            </div>
            @php
                use App\Models\DM_DotDanhGia; 
                $hienHanh = DM_DotDanhGia::where('HienHanh', 1)->with('hocKy')->first();
                if (!empty($hienHanh->hocKy)) echo("<div><span>Học kỳ {$hienHanh->hocKy->hocky} năm học {$hienHanh->hocKy->nambatdau} - {$hienHanh->hocKy->namketthuc}</span></div>")
            @endphp
            <div class='nav-right position-relative'>
                <div onClick='openDropdown()'>
                    <img class='rounded-circle' src='/images/logo.png' />
                    <span>
                        @if (!empty(Session::get('gv')))
                        {{ Session::get('gv')->chucdanh }}.{{ Session::get('gv')->hodem }} {{ Session::get('gv')->ten }} 
                        @endif
                    </span>
                </div>
                <div id="drop-down" class='position-absolute user-dropdown d-none'>
                    <div>
                        <div class='dropdown-arrow' style="
                        position: absolute;
                        display: block;
                        width: 8.5px;
                        background: transparent;
                        height: 8.5px;
                        border: 4.25px solid white;
                        transform: rotate(45deg);
                        /* z-index: -1; */
                        top: -5px;
                        left: 71px;
                    "></div>
                        <div class='user-dropdown-content bg-white '
                        style='box-shadow: rgb(0 0 0 / 20%) 0px 2px 10px; border-radius: 4px; '>
                            <a  href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();"
                                class='dropdown-tag w-100 d-flex' style="padding: 7px 15px">
                                <span><i class='fa fa-sign-out'></i></span>
                                <span class="ps-2">Logout</span>
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>
<script>

    function openMenu() {
        console.log('sss')
    }
</script>

app/resources/views/layouts/admin/sidebar.blade.php
<div class="h-100 sider  position-relative" id='sider' style='background-color: #2A3F54;'>
    <div class='h-100 overflow-hidden'>
        <div class="text-center logo-container">
            <h3 class='m-0'>
                <a href="/" class='text-decoration-none text-white text-uppercase'>VKU</a>
            </h3>
        </div>
        <div class='position-relative w-100 menu-wrap sidebar-left'
            style='height: calc(100% - 70px); max-height: calc(100% - 70px);'>
            <div class='position-absolute top-0'
                style='position: absolute; top: 0px; left: 0px; right: 0px; bottom: 0px; margin-right: 0px; margin-bottom: 0px;'>
                
                <div class="ps-2 pe-2 menu-item-inline @if (\Request::is('admin/DM_DiemRenLuyen') || \Request::is('admin/DM_DiemRenLuyen/*')) menu-item-selected @endif">
                    <button type="button" class="btn d-flex align-items-center justify-content-center">
                        <a class='text-decoration-none text-white' href="{{ route('admin.DM_DiemRenLuyen.index') }}">
                            <span style='color: rgb(120, 129, 149)' class="children-item">
                                <i class='fa fa-street-view'></i>
                                <span class='ps-3 menu-inline-text menu-tille' id='menu-text'>Điểm rèn luyện</span>
                            </span>
                        </a>
                    </button>
                </div>
                <div class="ps-2 pe-2 menu-item-inline @if (\Request::is('admin/DM_MauTieuChi') || \Request::is('admin/DM_MauTieuChi/*')) menu-item-selected @endif">
                    <button type="button" class="btn d-flex align-items-center justify-content-center">
                        <a class='text-decoration-none text-white' href="{{ route('admin.DM_MauTieuChi.index') }}">
                            <span style='color: rgb(120, 129, 149)' class="children-item">
                                <i class='fa fa-street-view'></i>
                                <span class='ps-3 menu-inline-text menu-tille' id='menu-text'>Mẫu tiêu chí</span>
                            </span>
                        </a>
                    </button>
                </div>
                <div class="ps-2 pe-2 menu-item-inline @if (\Request::is('admin/DM_DotDanhGia') || \Request::is('admin/DM_DotDanhGia/*')) menu-item-selected @endif">
                    <button type="button" class="btn d-flex align-items-center justify-content-center">
                        <a class='text-decoration-none text-white' href="{{ route('admin.DM_DotDanhGia.index') }}">
                            <span style='color: rgb(120, 129, 149)' class="children-item">
                                <i class='fa fa-street-view'></i>
                                <span class='ps-3 menu-inline-text menu-tille' id='menu-text'>Đợt đánh giá</span>
                            </span>
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

@section('js')
@parent
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
<script>

</script>
<script>
    function openSider() {
        document.getElementById("sider")?.classList.toggle('closeSider');
        document.getElementById("nav")?.classList.toggle('togge-padding-left');
    }
    // document.getElementById(window.location.href.split("/").pop())?.classList.add('menu-item-selected');
    // var id = ['id1', 'id2']
    // function openMenu() {
    //     for (const key in id) {
    //         document.getElementById(id[key])?.classList.toggle('d-none');
    //     }
    // }


</script>

@endsection